---
- name: Parchado Reto 1
  # A quienes se les va a operar 
  hosts: web
  become: true
  tasks: 
    - name: Actulizaciones
      ansible.builtin.dnf:
       name: "*"
       state: lastest
    - name: Validar Necesidad Reinicio
      ansible.builtin.command: needs-restarting
      register: need_restart
      failed_when: false
    - name: Reinicio
      ansible.builtin.reboot:
       msg: "Reinicio despues de aplicar actualizaciones"
       when: need_restart.rc == 1
...
